apiVersion: v1
kind: Service
metadata:
  name: go-web-app
  labels:
    app: go-web-app
spec:
  ports:
  - port: 80  # External port to access the service
    targetPort: 8080  # The port where your Go app listens inside the pod
    protocol: TCP
    nodePort: 30000  # NodePort to expose the service (can be any port between 30000-32767)
  selector:
    app: go-web-app
  type: NodePort  # Change from ClusterIP to NodePort for external access

